name: Conveyor Build
env:
  PROJECT_NAME: Conveyor
on_failure: "echo 'Build failed!'"
on_success: "echo 'Build successful!'"

jobs:
  - name: Build
    steps:
      - name: Compile
        command: cargo build
  - name: Test
    needs: ["Build"]
    env:
      RUST_BACKTRACE: "1"
    steps:
      - name: Unit Tests
        command: cargo test
  - name: Lint
    steps:
      - name: Check
        command: cargo clippy
